<?php
    // variable super global
    $archivo = $_FILES['archivo'];
    // var_dump($archivo);

    $nombre = $archivo['name'];
    $tipo = $archivo['type'];

    $destino = 'images';
    $rutaCompleta = '';

    if($tipo == 'image/jpg' || $tipo == 'image/jpeg' || $tipo == 'image/png' || $tipo == 'image/gif'){
        if(!is_dir($destino)){
            mkdir($destino, 0777);
        }
        
        $rutaCompleta .= $destino;
        $rutaCompleta .= '/';
        $rutaCompleta .= $nombre;
        
        // error messages that might be generated by that expression will be ignored
        @move_uploaded_file($archivo['tmp_name'], $rutaCompleta);
        header("Refresh: 3; URL=form.php");
        echo "<h1>Imagen subida Correctamente!</h1>";

    } else{
        header("Refresh: 2; URL=form.php");
        echo "<h1>suba una imagen con un formato correcto, por favor ...</h1>";
    }

    die();